/*
Package auth provides auto-generated TLS certificates and API token
authentication for the neutrino REST server.

tls.go handles self-signed certificate generation and loading.  On first
start the server creates an EC P-256 key pair and a self-signed X.509
certificate valid for localhost addresses.  The certificate is persisted
to the data directory so clients can pin it (trust-on-first-use, like SSH).
*/
package auth

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"time"

	"github.com/btcsuite/btclog"
)

const (
	// Default filenames inside the data directory.
	TLSCertFilename = "tls.cert"
	TLSKeyFilename  = "tls.key"

	// Certificate validity period (10 years, matching lnd).
	certValidityYears = 10
)

// TLSConfig holds paths and the loaded TLS configuration.
type TLSConfig struct {
	CertPath string
	KeyPath  string
	Config   *tls.Config
}

// LoadOrGenerateTLS returns a TLS configuration for the server.
// If cert/key files already exist they are loaded; otherwise a new
// self-signed certificate is generated and written to disk.
func LoadOrGenerateTLS(dataDir string, logger btclog.Logger) (*TLSConfig, error) {
	certPath := filepath.Join(dataDir, TLSCertFilename)
	keyPath := filepath.Join(dataDir, TLSKeyFilename)

	// Try loading existing cert/key first.
	if fileExists(certPath) && fileExists(keyPath) {
		logger.Infof("Loading TLS certificate from %s", certPath)
		tlsCfg, err := loadTLS(certPath, keyPath)
		if err != nil {
			logger.Warnf("Existing TLS files corrupt, regenerating: %v", err)
		} else {
			return &TLSConfig{CertPath: certPath, KeyPath: keyPath, Config: tlsCfg}, nil
		}
	}

	logger.Infof("Generating self-signed TLS certificate in %s", dataDir)
	if err := generateTLS(certPath, keyPath); err != nil {
		return nil, fmt.Errorf("failed to generate TLS certificate: %w", err)
	}

	tlsCfg, err := loadTLS(certPath, keyPath)
	if err != nil {
		return nil, fmt.Errorf("failed to load freshly generated TLS certificate: %w", err)
	}

	return &TLSConfig{CertPath: certPath, KeyPath: keyPath, Config: tlsCfg}, nil
}

// generateTLS creates a new self-signed EC P-256 certificate and writes
// PEM-encoded cert and key files.
func generateTLS(certPath, keyPath string) error {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("failed to generate private key: %w", err)
	}

	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
	if err != nil {
		return fmt.Errorf("failed to generate serial number: %w", err)
	}

	now := time.Now()
	template := x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{"neutrino-api"},
			CommonName:   "neutrino-api autogenerated cert",
		},
		NotBefore: now.Add(-time.Hour), // Small backdate for clock skew.
		NotAfter:  now.AddDate(certValidityYears, 0, 0),

		KeyUsage:              x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,

		// SANs for localhost connections.
		IPAddresses: []net.IP{
			net.IPv4(127, 0, 0, 1),
			net.IPv6loopback,
		},
		DNSNames: []string{"localhost"},
	}

	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		return fmt.Errorf("failed to create certificate: %w", err)
	}

	// Write certificate.
	certFile, err := os.OpenFile(certPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return fmt.Errorf("failed to create cert file: %w", err)
	}
	defer certFile.Close()
	if err := pem.Encode(certFile, &pem.Block{Type: "CERTIFICATE", Bytes: certDER}); err != nil {
		return fmt.Errorf("failed to write cert PEM: %w", err)
	}

	// Write private key (restricted permissions).
	keyDER, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return fmt.Errorf("failed to marshal private key: %w", err)
	}
	keyFile, err := os.OpenFile(keyPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("failed to create key file: %w", err)
	}
	defer keyFile.Close()
	if err := pem.Encode(keyFile, &pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER}); err != nil {
		return fmt.Errorf("failed to write key PEM: %w", err)
	}

	return nil
}

// loadTLS loads a TLS certificate and key from PEM files.
func loadTLS(certPath, keyPath string) (*tls.Config, error) {
	cert, err := tls.LoadX509KeyPair(certPath, keyPath)
	if err != nil {
		return nil, err
	}
	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		MinVersion:   tls.VersionTLS12,
	}, nil
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}
